config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root :to => 'votes#index'

  get "/website/:website_id/upvote" => "votes#upvote", as: 'upvote'

  get "/website/:website_id/downvote" => "votes#downvote", as: 'downvote'

  match "faq" => "votes#faq", as: 'faq', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :website
  belongs_to :user
  validates :website, :user, :presence => true
end

app/models/website.rb
class Website < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def vote_params
    params.permit(:user, :website, :upvote)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
    @user = current_user()
    user_votes_count = Vote.where(:user => @user).count
    @user_votes_left = Website.all.count - user_votes_count
    # @all_votes_count = Vote.all.count

    if user_votes_count > 0 || params[:understand]
      @random_website = get_random_website(@user)
      @success = params[:success]

      if @random_website
        screenshot = 'http://dl.dropboxusercontent.com/u/2425826/wote/images/' + @random_website.url.gsub('http://www', '').gsub(/(\W|\d)/, '') + '.png'

        unless @random_website.screenshot == screenshot
          @random_website.screenshot = 'http://dl.dropboxusercontent.com/u/2425826/wote/images/' + @random_website.url.gsub('http://www', '').gsub(/(\W|\d)/, '') + '.png'
          @random_website.save!
        end
      end
    else
      if @user
        # renders faq just when user is logged in
        @show_next = true
        render :template => "votes/faq"
      else
        return
      end
    end
  end

  def upvote
    @website = Website.find(params[:website_id])

    @vote = Vote.new(vote_params)
    @vote.website = @website
    @vote.user = current_user()
    @vote.upvote = true

    respond_to do |format|
      begin
        @vote.save!
        format.html { redirect_to action: 'index', :status => :found, :success => 'true' }
      rescue ActiveRecord::RecordNotUnique
        format.html { redirect_to action: 'index', :status => :found, :success => 'false' }
      end
    end
  end

  def downvote
    @website = Website.find(params[:website_id])

    @vote = Vote.new(vote_params)
    @vote.website = @website
    @vote.user = current_user()
    @vote.upvote = false

    respond_to do |format|
      begin
        @vote.save!
        format.html { redirect_to action: 'index', :status => :found, :success => 'true' }
      rescue ActiveRecord::RecordNotUnique
        format.html { redirect_to action: 'index', :status => :found, :success => 'false' }
      end
    end
  end

  #def generate_all
  #  websites = Website.all
  #
  #  websites.each do |website|
  #    begin
  #      website_url = website.url
  #      directory_path = 'images/'
  #      website_path  = directory_path + website_url.gsub('http://www', '').gsub(/(\W|\d)/, "") + '.png'
  #
  #      unless File.exist?('public/' + website_path)
  #        ws = Webshot::Screenshot.instance
  #
  #        ws.capture website_url, 'public/' + website_path, width: 1000, height: 1000, quality: 95
  #      end
  #    rescue Exception => ex
  #      next
  #    end
  #  end
  #end

  def faq

  end

  private
  def is_website_already_voted(user, website)
    already_voted = false

    if Vote.where(user: user, website: website).count > 0
      already_voted = true
    end

    already_voted
  end

  def get_random_website(user)
    @random_website = nil

    if user
      websites = Website.where("websites.id NOT IN (SELECT website_id FROM Votes WHERE user_id=#{user.id})")

      if websites.count() > 0
        @random_website = websites.shuffle.first
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Wote</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <!-- Static navbar -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Wote</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav navbar-nav">
                    <li><a href="<%= root_path %>">Home</a></li>
                    <li><a href="<%= faq_path %>">FAQ</a></li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <% if current_user %>
                        <li class="dropdown">
                            <a id="sign_out" class="dropdown-toggle" data-toggle="dropdown" href="<%= signout_path %>">
                                Welcome <strong><%= current_user.name %></strong> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <%= link_to "Sign out", signout_path, id: "sign_out" %>
                                </li>
                            </ul>
                        </li>
                    <% else %>
                        <li>
                            <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">
        <%= yield %>
    </div>
</div>
</body>
</html>

app/views/votes/faq.html.erb
<div class="faq">
    <h3>Who am I?</h3>
    <p>Hey, my name is <a href="http://si.linkedin.com/in/dperic/" target="_blank">Dražen</a>, I'm working as a web developer for <a href="http://www.astina.ch" target="_blank">Astina</a> and I'm writing my final exam at <a href="http://www.fri.uni-lj.si/en/" target="_blank">Faculty of Computer and Information Science</a> in Ljubljana. I also do bunch of other things, but that's irrelevant now.</p>
    <h3>Why do I need your help here?</h3>
    <p>As I mentioned, at the moment I'm working on my <strong>final exam</strong>. My topic is called <strong>"Modeling relation between technical parameters of web page design and its aesthetics"</strong> and this is basically also a short description that topic.<br>For this purpose, I need data that will help me to build my learning set, which I'll be using in later stages. To get this data, I need you and I need your ratings.</p>
    <h3>And how does it work?</h3>
    <p>So, here I basically have a set of 200 websites which have to be evaluated. What I'm asking you is one simple thing - when you see a website, just tell me whether you like it or not - click on the buttons, or click on the left (don't like) or on the right (like) side of the image - do not evaluate whether website is functional or not, <strong>just tell if you like the page visually or not</strong>. After you vote for one page, it gets disappeared and another one appears - so it's a basically a "Hot or Not" for websites :)</p>
    <h3>What's the deal with Facebook login? What about my data?</h3>
    <p>Well the answer it's simple - I'm using Facebook login because it was the simplest solution and I didn't need to deal with user registrations, profiles and so on. So basically, with Facebook login, the only data that's stored in this application is just your name which will not be used anywhere.</p>
    <h3>And for how long do I need to "vote"?</h3>
    <p>Do it as long as you want. I really need quite some amount of data but I don't want to force people to do something they don't like, so you decide ;)</p>
    <h3>More tips?</h3>
    <p>Well, try to not be related to websites too personally - I just want to know whether you like visual design of it or not.</p>
    <h3>I'm experiencing problems with this voting app - what is going on?</h3>
    <p>This is a custom solution and because of that I've had some issues with it because some screenshots couldn't be generated, then screenshot images were not reachable anymore etc. Anyway, now it should be everything back to normal. Sorry for the inconvenience.</p>
    <h3>Any questions?</h3>
    <p>Feel free to contact me - <span class="reverse">moc.liamg@nehzard.cirep</span></p>
</div>

<% if @show_next %>
    <div class="text-center">
        <a class="btn btn-primary ladda-button understand" data-style="expand-left" href="<%= root_path(:understand => 'true') %>">
            <span class="ladda-label">I understand</span>
        </a>
        <span style="display: block; margin-top: 10px;">
            Click the button to continue (and yes, you can always come back here by clicking to "FAQ" link)
        </span>
    </div>
<% end %>

app/views/votes/index.html.erb
<% if current_user() %>
    <% if @random_website %>
        <% upvote_url = upvote_path(@random_website) %>
        <% downvote_url = downvote_path(@random_website) %>
        <% if @success.nil? %>
            <h1 class="text-center">Do you find this webpage design attractive?</h1>
        <% elsif @success == 'true' %>
            <h2 class="text-center">Hey, thanks for voting, keep on going. There is <%= @user_votes_left %> websites left to vote.</h2>
        <% else %>
            <h2 class="text-center">Hm, looks like something went wrong - but keep on going anyway.</h2>
        <% end %>
        <div class="website-holder">
            <form action="" method="get">
                <div class="vote-buttons vote-buttons-top text-center">
                    <button type="button" class="btn btn-primary vote-button vote-downvote" title="downvote" data-url="<%= downvote_url %>">
                        <span class="glyphicon glyphicon-thumbs-down"></span>
                    </button>
                    <button type="button" class="btn btn-primary vote-button vote-upvote" title="upvote" data-url="<%= upvote_url %>">
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                    </button>
                </div>
                <div class="website"<% if @random_website.screenshot %>style="background: url('<%= @random_website.screenshot %>') no-repeat;"<% end %>>
                    <div class="website-half-image vote-downvote" data-url="<%= downvote_url %>">
                        <div class="overlay">
                            <span class="glyphicon glyphicon-thumbs-down character"></span>
                        </div>
                    </div>
                    <div class="website-half-image vote-upvote" data-url="<%= upvote_url %>">
                        <div class="overlay">
                            <span class="glyphicon glyphicon-thumbs-up character"></span>
                        </div>
                    </div>
                </div>
                <div class="vote-buttons vote-buttons-bottom text-center">
                    <button type="button" class="btn btn-primary vote-button vote-downvote" title="downvote" data-url="<%= downvote_url %>">
                        <span class="glyphicon glyphicon-thumbs-down"></span>
                    </button>
                    <button type="button" class="btn btn-primary vote-button vote-upvote" title="upvote" data-url="<%= upvote_url %>">
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                    </button>
                </div>
                <div class="text-center link-to-website">
                    <%= link_to @random_website.url, @random_website.url, :target => "_blank" %>
                </div>
            </form>
        </div>
    <% else %>
        <h2 class="text-center">Whoooaah, looks like there's no more websites to vote for :(</h2>
        <h2 class="text-center">But thanks for your help. srsly! ;)</h2>
    <% end %>
<% else %>
    <h1 class="text-center">
        Please login with Facebook to play.
        <%= link_to "Click to login", "/auth/facebook", id: "sign_in" %>.
    </h1>
<% end %>

app/views/votes/why.html.erb
<div class="faq">
    <h3>Who am I?</h3>
    <p>Hey, my name is <a href="http://si.linkedin.com/in/dperic/" target="_blank">Dražen</a>, I'm working as a web developer for <a href="http://www.astina.ch" target="_blank">Astina</a> and I'm writing my final exam at <a href="http://www.fri.uni-lj.si/en/" target="_blank">Faculty of Computer and Information Science</a> in Ljubljana. I also do bunch of other things, but that's irrelevant now.</p>
    <h3>Why do I need your help here?</h3>
    <p>As I mentioned, at the moment I'm working on my <strong>final exam</strong>. My topic is called <strong>"Modeling relation between technical parameters of web page design and its aesthetics"</strong> and this is basically also a short description that topic.<br>For this purpose, I need data that will help me to build my learning set, which I'll be using in later stages. To get this data, I need you and I need your ratings.</p>
    <h3>And how does it work?</h3>
    <p>So, here I basically have a set of 600 websites which have to be evaluated. What I'm asking you is one simple thing - when you see a website, just tell me whether you like it or not - click on the buttons, or click on the left (don't like) or on the right (like) side of the image - do not evaluate whether website is functional or not, <strong>just tell if you like the page visually or not</strong>. After you vote for one page, it gets disappeared and another one appears - so it's a basically a "Hot or Not" for websites :)</p>
    <h3>What's the deal with Facebook login? What about my data?</h3>
    <p>Well the answer it's simple - I'm using Facebook login because it was the simplest solution and I didn't need to deal with user registrations, profiles and so on. So basically, with Facebook login, the only data that's stored in this application is just your name which will not be used anywhere.</p>
    <h3>More tips?</h3>
    <p>Well, try to not be related to websites too personally - I just want to know whether you like visual design of it or not.</p>
</div>